name: Java ci with Maven

#Trigger
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install

      - name: Run Maven tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t task-mgnt-service .

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push Docker Image
        run: |
          docker tag task-mgnt-service ${{secrets.DOCKER_USERNAME}}/task_mgnt_service:latest \
          && docker push ${{secrets.DOCKER_USERNAME}}/task_mgnt_service:latest